### ISSUE TITLE
http://typescript.ninja/typescript-in-definitelyland/ が閲覧できない状態のようです

### ISSUE THREAD

**Issue by shimobayashi** [typescript-ninja/typescript-in-definitelyland#18]
はじめまして、最近こちらの本でTypeScriptの勉強をさせていただいています。

ところで現在、
https://github.com/typescript-ninja/typescript-in-definitelyland#web%E3%82%B5%E3%82%A4%E3%83%88%E3%81%A8%E3%81%97%E3%81%A6%E9%96%B2%E8%A6%A7%E3%81%99%E3%82%8B%E5%A0%B4%E5%90%88
からリンクされている
http://typescript.ninja/typescript-in-definitelyland/ 
が閲覧できない状態のようです。

```
$ curl -D - http://typescript.ninja/typescript-in-definitelyland/
HTTP/1.1 500 Domain Not Found
Server: Varnish
Retry-After: 0
content-type: text/html
Cache-Control: private, no-cache
connection: keep-alive
X-Served-By: cache-lax8645-LAX
Content-Length: 252
Accept-Ranges: bytes
Date: Thu, 13 Feb 2020 13:38:35 GMT
Via: 1.1 varnish
Connection: keep-alive


<html>
<head>
<title>Fastly error: unknown domain typescript.ninja</title>
</head>
<body>
<p>Fastly error: unknown domain: typescript.ninja. Please check that this domain has been added to a service.</p>
<p>Details: cache-lax8645-LAX</p></body></html>
```

もしかしたら認知されていないかも？と思い、念の為共有させていただきます。

**Comment by vvakame** [comment]
おっ認知してませんでしたありがとうございます…！(このIssueに気がつくのもめちゃ遅かったですね…すみません…

**Comment by vvakame** [comment]
直せましたー だいぶ忘れてたので危なかった…
Google Domainsでapex domainに対して適当にAレコード設定してた
https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain

**Comment by shimobayashi** [comment]
閲覧できました！
おつかれさまです！
